[build]
  command = "npm run build"
  publish = "dist"

# SPA routing: send all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy: point this to your deployed backend URL
# Replace https://YOUR-BACKEND-URL with your actual backend host
[[redirects]]
  from = "/api/*"
  to = "https://studentattendence23.netlify.app/.netlify/functions/api/:splat"
  status = 200
